# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."seafile" = {
    image = "seafileltd/seafile-mc:12.0-latest";
    environmentFiles = [
      "/home/martijn/.flake/services/seafile/seafile.env"
      "/run/agenix/seafile-secrets.env"
    ];
    volumes = [
      "/opt/seafile-data:/shared:rw"
    ];
    ports = [
      "127.0.0.1:8083:80/tcp"
    ];
    labels = {
      "caddy" = "https://seafile.martijnv.com";
      "caddy.reverse_proxy" = "{{upstreams 80}}";
    };
    dependsOn = [
      "seafile-memcached"
      "seafile-mysql"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=seafile"
      "--network=seafile-net"
    ];
  };
  systemd.services."docker-seafile" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "docker-network-seafile-net.service"
    ];
    requires = [
      "docker-network-seafile-net.service"
    ];
    partOf = [
      "docker-compose-seafile-root.target"
    ];
    wantedBy = [
      "docker-compose-seafile-root.target"
    ];
  };
  virtualisation.oci-containers.containers."seafile-memcached" = {
    image = "memcached:1.6.29";
    environmentFiles = [
      "/home/martijn/.flake/services/seafile/seafile.env"
      "/run/agenix/seafile-secrets.env"
    ];
    log-driver = "journald";
    extraOptions = [
      "--entrypoint=[\"memcached\", \"-m\", \"256\"]"
      "--network-alias=memcached"
      "--network=seafile-net"
    ];
  };
  systemd.services."docker-seafile-memcached" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "docker-network-seafile-net.service"
    ];
    requires = [
      "docker-network-seafile-net.service"
    ];
    partOf = [
      "docker-compose-seafile-root.target"
    ];
    wantedBy = [
      "docker-compose-seafile-root.target"
    ];
  };
  virtualisation.oci-containers.containers."seafile-mysql" = {
    image = "mariadb:10.11";
    environmentFiles = [
      "/home/martijn/.flake/services/seafile/seafile.env"
      "/run/agenix/seafile-secrets.env"
    ];
    volumes = [
      "/opt/seafile-mysql/db:/var/lib/mysql:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=[\"/usr/local/bin/healthcheck.sh\", \"--connect\", \"--mariadbupgrade\", \"--innodb_initialized\"]"
      "--health-interval=20s"
      "--health-retries=10"
      "--health-start-period=30s"
      "--health-timeout=5s"
      "--network-alias=db"
      "--network=seafile-net"
    ];
  };
  systemd.services."docker-seafile-mysql" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "docker-network-seafile-net.service"
    ];
    requires = [
      "docker-network-seafile-net.service"
    ];
    partOf = [
      "docker-compose-seafile-root.target"
    ];
    wantedBy = [
      "docker-compose-seafile-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-seafile-net" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f seafile-net";
    };
    script = ''
      docker network inspect seafile-net || docker network create seafile-net
    '';
    partOf = [ "docker-compose-seafile-root.target" ];
    wantedBy = [ "docker-compose-seafile-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-seafile-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
